spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/member/**


logging:
  file:
    path: ./log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info

