spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8081
          predicates:
            - Path=/member/**
        - id: business
          uri: http://127.0.0.1:8082
          predicates:
            - Path=/business/**
        - id: batch
          uri: http://127.0.0.1:8083
          predicates:
            - Path=/batch/**

logging:
  file:
    path: ./log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info

